# Generated by Django 4.1.1 on 2022-10-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatexRenderCache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expression', models.TextField()),
                ('svg', models.TextField()),
            ],
        ),
    ]
